name: Latest blog post workflow

on:
  schedule:
    - cron: '0 4 * * *' 
  workflow_dispatch: 

jobs:
  update_readme_blog_articles:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://krypton.ninja/rss.xml"
          committer_username: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com