name: Waka Readme

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: 

jobs:
  update-readme:
    name: Update this repo's README with time spent on
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMITTER_NAME: github-actions[bot]
          COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
